icons_format = "{icon}"

[theme]
theme = "ctp-mocha"
[theme.overrides]
idle_bg = "#0000004d" # keep this the same as bar color in i3

[icons]
icons = "awesome4"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "battery"
# interval = 60
good = 100
warning = 45
critical = 15

[[block]]
block = "cpu"
info_cpu = 80
warning_cpu = 85
critical_cpu = 95

# [[block]]
# block = "disk_space"
# path = "/"
# info_type = "available"
# alert_unit = "GB"
# interval = 20
# warning = 20.0
# alert = 10.0
# format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2) "
# format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "

