#!/bin/dash

BAT=$(acpi -b | grep -E -o '[0-9][0-9]?%')
# BAT=71%
PERCENTAGE=${BAT%?}

get_battery_icon() {
  if [ $PERCENTAGE -ge 90 ]; then
    echo " "
  elif [ $PERCENTAGE -ge 70 ]; then
    echo " "
  elif [ $PERCENTAGE -ge 40 ]; then
    echo " "
  elif [ $PERCENTAGE -ge 16 ]; then
    echo " "
  else
    echo " "
  fi
}

BATTERY_ICON=$(get_battery_icon)

echo "$BATTERY_ICON $BAT"

# Set urgent flag below 5% or use orange below 15%
[ $PERCENTAGE -le 5 ] && exit 33
[ $PERCENTAGE -le 15 ] && exit 33

exit 0

